=== zmryasmine/Projet_DPR/donnees_recettes_transform.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
    <xs:element name="site">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="recettes"/>
                <xs:element ref="listes_ingredients"/>
                <xs:element ref="auteurs"/>
                <xs:element ref="categories"/>
                <xs:element ref="sous-categories"/>
                <xs:element ref="produits"/>
            </xs:sequence>
            <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="recettes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="recette"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="recette">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="titre-recette" name ="nom"/>
                <xs:element ref="resume"/>
                <xs:element minOccurs="1" maxOccurs="20" name="ref-ingredient" type="ref-ingredient-recette"/>
                <xs:element name="ref-souscategorie" type="ref"/>
                <xs:element name="ref-auteur" type="ref"/>
                <xs:element ref="photo"/>
                <xs:element ref="date_publication"/>
                <xs:element ref="difficulté"/>
                <xs:element ref="nbre_personnes"/>
                <xs:element ref="temps_prep"/>
                <xs:element ref="temps_cuisson"/>
                <xs:element ref="temps_repos"/>
                <xs:element ref="preparation"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="note"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="resume" type="xs:string"/>

    <xs:element name="photo" type="xs:anyURI"/>
    <xs:element name="date_publication" type="xs:NMTOKEN"/>
    <xs:element name="difficulté" type="xs:string"/>
    <xs:element name="nbre_personnes" type="xs:integer"/>
    <xs:element name="temps_prep" type="xs:NMTOKEN"/>
    <xs:element name="temps_cuisson" type="xs:string"/>
    <xs:element name="temps_repos" type="xs:string"/>
    <xs:element name="preparation">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="p"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="note" type="xs:string"/>
    <xs:element name="listes_ingredients">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ingredient"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ingredient">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="apport_energetique"/>
                <xs:element ref="apport_nutritif"/>
                <xs:element ref="saison"/>
                <xs:element ref="descriptif"/>
                <xs:element maxOccurs="unbounded" name="ref-recette" type="ref"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="apport_energetique" type="xs:string"/>
    <xs:element name="apport_nutritif" type="xs:string"/>
    <xs:element name="saison" type="xs:string"/>
    <xs:element name="auteurs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="auteur"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="auteur">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="prenom"/>
                <xs:element ref="age"/>
                <xs:element ref="pays"/>
                <xs:element ref="genre"/>
                <xs:element ref="bio"/>
                <xs:element maxOccurs="unbounded" name="ref-recette" type="ref"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="prenom" type="xs:NCName"/>
    <xs:element name="age">
        <xs:complexType/>
    </xs:element>
    <xs:element name="pays" type="xs:NCName"/>
    <xs:element name="genre" type="xs:NCName"/>
    <xs:element name="bio">
        <xs:complexType/>
    </xs:element>
    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="categorie" type="CategorieType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sous-categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="sous-categorie" type="SousCategorieType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="produits">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="produit"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="produit">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element maxOccurs="unbounded" name="ref-ingredient" type="ref"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nom" type="xs:string"/>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="p"/>
                <xs:element ref="br"/>
                <xs:element ref="strong"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType/>
    </xs:element>
    <xs:element name="strong" type="xs:string"/>
    <xs:element name="descriptif">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="p"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="titre-recette">
        <xs:restriction base="xs:string">
            <xs:minLength value="2"/>
            <xs:maxLength value="70"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ref-ingredient-recette">
        <xs:complexContent>
            <xs:extension base="ref">
                <xs:attribute name="quantite" use="required" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ref">
        <xs:attribute name="ref" use="required" type="xs:NCName"/>
    </xs:complexType>

    <xs:complexType name="SousCategorieType">
        <xs:sequence>
            <xs:element ref="nom"/>
            <xs:element ref="descriptif"/>
            <xs:element name="ref-categorie" type="ref"/>
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>

    <xs:complexType name="CategorieType">
        <xs:complexContent>
            <xs:restriction base="SousCategorieType">
                <xs:sequence>
                    <xs:element ref="nom"/>
                    <xs:element ref="descriptif"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== zmryasmine/Projet_DPR/donnees_recettes_transform.xml
<?xml version="1.0" encoding="UTF-8"?><site xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="donnees_recettes_transform.xsd">
    <recettes>
        <recette id="r2830">
            <nom>Cake à la tomate farcie</nom>
            <resume>
				Cake à la tomate farcie - Recettes de cuisine Ôdélices
			</resume>
            <ref-ingredient ref="F120" quantite="100g"/>
            <ref-ingredient ref="L300" quantite="1 cuillère à café rase"/>
            <ref-ingredient ref="L50" quantite="7,5 cl"/>
            <ref-ingredient ref="O12" quantite="1"/>
            <ref-ingredient ref="H20" quantite="1 cuillère à soupe"/>
            <ref-ingredient ref="t142" quantite="1 petite boite "/>
            <ref-ingredient ref="F10" quantite="30 g"/>
            <ref-ingredient ref="t120" quantite="6 grappes"/>
            <ref-ingredient ref="S12" quantite=""/>
            <ref-ingredient ref="Po40" quantite=""/>
            <ref-souscategorie ref="SC1"/>
            <ref-auteur ref="AUT3"/>
            <photo>http://www.odelices.com/images/recettes/cake-a-la-tomate-farcie.jpg</photo>
            <date_publication>2011-04-24</date_publication>
            <difficulté>Très facile</difficulté>
            <nbre_personnes>6</nbre_personnes>
            <temps_prep>20min</temps_prep>
            <temps_cuisson>25min</temps_cuisson>
            <temps_repos/>
            <preparation>
                <p>
                    1. Inciser le fond de chaque tomate et vider les graines à l'aide d'une toute petite cuillère (j'ai fait avec le manche d'une cuillère à moka).
Saler l'intérieur de chaque tomate et déposer sur un papier absorbant, elles vont dégorger.

                    <br/>
                    2. Beurrer et fariner 6 ramequins. Préchauffer le four à 180°C.
                    <br/>
                    3. Faire tiédir le lait 20-30 secondes au micro-onde. Battre l'oeuf en omelette, saler et poivrer puis ajouter la farine, la levure, le lait et l'huile. 
 Ajouter le fromage râpé.
                    <br/>
                    4. Dans un bol mélanger la fêta et le thon égoutté à l'aide d'une fourchette et farcir les tomates avec cette préparation.

                    <br/>
                    5. Remplir les moules avec la pâte et déposer une tomate dans chaque en l'enfonçant au deux tiers du moule.

                    <br/>
                    6. Cuire entre 20 et 25 minutes.
                </p>
            </preparation>
            <note/>
        </recette>
        <recette id="r3136">
            <nom>Petits cakes au chèvre frais et myrtilles</nom>
            <resume>
				 Petits cakes au chèvre frais et myrtilles - les meilleures recettes de cuisine d'Ôdélices
			</resume>
            <ref-ingredient ref="F120" quantite="250 g"/>
            <ref-ingredient ref="L50" quantite="15cl"/>
            <ref-ingredient ref="O12" quantite="4"/>
            <ref-ingredient ref="H20" quantite="5cl"/>
            <ref-ingredient ref="FC20" quantite="2"/>
            <ref-ingredient ref="B200" quantite="1/4 cuillerée à café"/>
            <ref-ingredient ref="M110" quantite="100 g"/>
            <ref-souscategorie ref="SC1"/>
            <ref-auteur ref="AUT2"/>
            <photo>http://www.odelices.com/images/recettes/petits-cakes-au-chevre-frais-et-myrtilles.jpg</photo>
            <date_publication>2012-04-09</date_publication>
            <difficulté>Très facile</difficulté>
            <nbre_personnes>6</nbre_personnes>
            <temps_prep>10min</temps_prep>
            <temps_cuisson>17min</temps_cuisson>
            <temps_repos/>
            <preparation>
                <p>
                    1. Dans un saladier, mélangez la farine, le sel, le bicarbonate, les oeufs, le lait et l'huile.
                    <br/>
                    2. Quand la pâte est belle, versez-la dans de petits moules à cake huilés.
                    <br/>
                    3. Répartissez sur les cakes de petits morceaux de fromage et les myrtilles.
                    <br/>
                    4. Faites cuire 17 minutes à 180°C four ventilé. Piquez un cake à l'aide de la pointe d'un couteau afin de vérifier la cuisson.
                    <br/>
                    5. Servez à température ambiante avec une salade croquante.
                    <br/>
                    			
                </p>
            </preparation>
            <note>5</note>
        </recette>
        <recette id="r4275">
            <nom>Mozzarella panée</nom>
            <resume>
				Pour un soir de semaine, si vous voulez faire une salade express mais épatante, faites de la mozzarella panée ! C'est rapide, facile et très syma !

			</resume>
            <ref-ingredient ref="B10" quantite="2"/>
            <ref-ingredient ref="O12" quantite="1"/>
            <ref-ingredient ref="F120" quantite="4 cuillerées à soupe"/>
            <ref-ingredient ref="CH12" quantite="1 petit bol"/>
            <ref-souscategorie ref="SC2"/>
            <ref-auteur ref="AUT1"/>
            <photo>http://www.odelices.com/images/recettes/mozzarella_panee.jpg</photo>
            <date_publication>2015-02-08</date_publication>
            <difficulté>Très facile</difficulté>
            <nbre_personnes>4</nbre_personnes>
            <temps_prep>5min</temps_prep>
            <temps_cuisson>5min</temps_cuisson>
            <temps_repos/>
            <preparation>
                <p>
                    1. Coupez les boules de mozzarella en rondelles.
                    <br/>
                    2. Mettez la farine et la chapelure dans deux assiettes. Et battez l'oeuf avec une fourchette dans un bol.
                    <br/>
                    3. Faites chauffer une poêle avec de l'huile.
                    <br/>
                    4. Faites tremper les rondelles de mozzarella dans la farine, puis dans l'oeuf et enfin dans la chapelure.
                    <br/>
                    5. Faites frire dans la poêle quelques minutes de chaque côté. Servez avec une salade verte.
                    <br/>
                    			
                </p>
            </preparation>
            <note>5</note>
        </recette>
        <recette id="r3289">
            <nom>Oeuf cocotte aux marrons</nom>
            <resume/>
            <ref-ingredient ref="M9" quantite="200 g"/>
            <ref-ingredient ref="O12" quantite="4"/>
            <ref-ingredient ref="C50" quantite="4 cuillerées à soupe"/>
            <ref-ingredient ref="S12" quantite=""/>
            <ref-ingredient ref="Po40" quantite=""/>
            <ref-souscategorie ref="SC2"/>
            <ref-auteur ref="AUT1"/>
            <photo>http://www.odelices.com/images/recettes/oeuf_cocotte_aux_marrons.jpg</photo>
            <date_publication>2012-11-22</date_publication>
            <difficulté>Très facile</difficulté>
            <nbre_personnes>4</nbre_personnes>
            <temps_prep>5min</temps_prep>
            <temps_cuisson>15min</temps_cuisson>
            <temps_repos/>
            <preparation>
                <p>
                    1. Hachez grossièrement les marrons cuits. Répartissez-les dans 4 ramequins inviduels.
                    <br/>
                    2. Répartissez une cuillère de crème sur les marrons.
                    <br/>
                    3. Puis cassez les oeufs et ajoutez-en un dans chaque ramequin, en les posant délicatement pour ne pas casser le jaune. Salez et poivrez.
                    <br/>
                    4. Placez les ramequins dans le four préchauffé à 180°C, au bain-marie. Faites cuire 15 min jusqu'à ce que le blanc soit bien pris.
                    <br/>
                    5. Servez chaud, avec des mouillettes de pain grillé.
                    <br/>
                    			
                </p>
            </preparation>
            <note/>
        </recette>
        <recette id="r4315">
            <nom>Endives farcies au thon</nom>
            <resume>
				

Une salade « hébergée » dans une feuille d'endive ! Une idée gourmande qui ravira les plus jeunes qui pourront d'ailleurs vous aider à farcir les endives !
			</resume>
            <ref-ingredient ref="e300" quantite="2"/>
            <ref-ingredient ref="t120" quantite="2"/>
            <ref-ingredient ref="Co30" quantite="6"/>
            <ref-ingredient ref="C50" quantite="2 cuillerées à soupe"/>
            <ref-ingredient ref="M80" quantite="2 cuillerées à soupe"/>
            <ref-ingredient ref="CI10" quantite="50 g"/>
            <ref-ingredient ref="t142" quantite="10 brins"/>
            <ref-ingredient ref="S12" quantite=""/>
            <ref-ingredient ref="Po40" quantite=""/>
            <ref-souscategorie ref="SC3"/>
            <ref-auteur ref="AUT1"/>
            <photo>http://www.odelices.com/images/recettes/endives_farcies_au_thon1.jpg</photo>
            <date_publication>2015-03-12</date_publication>
            <difficulté>Très facile</difficulté>
            <nbre_personnes>4</nbre_personnes>
            <temps_prep>15min</temps_prep>
            <temps_cuisson/>
            <temps_repos/>
            <preparation>
                <p>
                    1. Lavez les tomates, coupez-les en deux et épépinez-les. Emincez finement la ciboulette.
                    <br/>
                    2. Mettez dans le bol du robot le thon, les tomates, les cornichons, la crème fraîche, la moutarde et la ciboulette. Mixez le tout grossièrement pour garder quelques morceaux. Salez légèrement et poivrez éventuellement.
                    <br/>
                    3. Passez les endives sous l'eau rapidement et enlevez le cône amer à la base des feuilles. Détachez les feuilles une par une, séchez-les bien.
                    <br/>
                    4. Répartissez la farce dans les feuilles et servez bien frais.
                </p>
            </preparation>
            <note/>
        </recette>
        <recette id="r1241">
            <nom>Moules et frites</nom>
